/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx,ts,tsx,mdx}",
    "./components/**/*.{js,jsx,ts,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f8",
        background: "#fbf9f8",
        tertiary: "#535f70",
        "on-background": "#1b1c1c",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f5f3f3",
        "inverse-primary": "#7ad0ff",
        "tertiary-container": "#919db0",
        "surface-dim": "#dbdad9",
        "on-tertiary-fixed": "#101c2b",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#643900",
        "primary-fixed-dim": "#7ad0ff",
        "inverse-surface": "#303030",
        "surface-container-high": "#eae8e7",
        "surface-container": "#efeded",
        secondary: "#8a5100",
        "on-tertiary-fixed-variant": "#3c4858",
        "on-secondary-fixed": "#2c1600",
        "on-primary-container": "#00384e",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        outline: "#6e7980",
        "surface-container-highest": "#e4e2e2",
        "on-tertiary-container": "#293544",
        "primary-container": "#00a8e1",
        primary: "#00668a",
        "surface-tint": "#00668a",
        "tertiary-fixed": "#d7e3f7",
        "on-primary-fixed": "#001e2c",
        "secondary-container": "#fe9800",
        "tertiary-fixed-dim": "#bbc7db",
        "inverse-on-surface": "#f2f0f0",
        "primary-fixed": "#c3e7ff",
        "on-surface": "#1b1c1c",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdcbd",
        "secondary-fixed-dim": "#ffb86f",
        "outline-variant": "#bdc8d0",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fbf9f8",
        "surface-variant": "#e4e2e2",
        "on-surface-variant": "#3e484f",
        "on-primary-fixed-variant": "#004c69",
        "on-secondary-fixed-variant": "#693c00",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
